Little improvements in etcd_bootstrap_script.sh
gardener/etcd-custom-image pull request #28
Opened 2022-12-19 08:35 UTC by StenlyTU

**What this PR does / why we need it**:
Improve Indentation and readability.

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

2022-12-19 12:17 UTC, shreyas-s-rao requested changes
@StenlyTU thanks for your PR. I tested it locally and saw that etcd container throws the following error log:
```
standard_init_linux.go:228: exec user process caused: exec format error
```

Can you please check this? Thanks.

2023-01-04 06:55 UTC, unmarshall commented on etcd_bootstrap_script.sh
> +    if [ $arch = "aarch64" ] || [ $arch = "arm64" ]; then
Can you also enclose $arch in double quotes? This is usually done to prevent gobbling and word splitting.

2023-01-04 06:56 UTC, unmarshall commented on etcd_bootstrap_script.sh
> +                break ;;
This is unreachable line and should ideally be removed. Call to `start-managed-etcd` function has `exit` as the last statement which means break will never be called.

2023-01-04 06:58 UTC, unmarshall commented
> @StenlyTU thanks for your PR. I tested it locally and saw that etcd container throws the following error log:
> 
> ```
> standard_init_linux.go:228: exec user process caused: exec format error
> ```
> 
> Can you please check this? Thanks.

I think you have ARM based chipset. Can you check if this is not an issue with using the wrong image on built for another architecture?

2023-01-06 09:19 UTC, shreyas-s-rao commented
@StenlyTU we haven't heard anything from you from a while. We have started work on https://github.com/gardener/etcd-custom-image/issues/16, which would invalidate any changes you've made in this PR. So I would vote in favour of closing this PR since the changes made here don't bring any functional improvement, for the cost of making a new release of the etcd-custom-image for the same etcd version being used within gardener, given that we will be restructuring the repo, code and releases.
Are you ok with this suggestion?

2023-01-06 09:20 UTC, closed without merging